<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AddressDetailsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        DB::table('address_details')->delete();

        DB::table('address_details')->insert(array(
            0 =>
            array(
                'id' => 0,
                'address_id' => 0,
                'latitude' => '3.3144165',
                'longitude' => '101.4142867',
                'name' => NULL,
                'address_1' => 'Lot 769-1/2, Lot 770-1/2',
                'address_2' => 'Jalan Kuala SELANGOR',
                'postcode' => 45600,
                'city' => 'BESTARI JAYA',
                'state' => 'SELANGOR',
                'status' => 'Created',
                'type' => 'Office',
                'link' => NULL,
                'creator_id' => 0,
                'updated_at' => '2024-11-20 19:01:16',
                'created_at' => '2024-11-20 19:01:13',
            ),
            1 =>
            array(
                'id' => 1,
                'address_id' => 1,
                'latitude' => '3.0652032',
                'longitude' => '101.4614516',
                'name' => NULL,
                'address_1' => 'A-18-3A, Blok A, Pangsapuri Palm Garden',
                'address_2' => 'Persiaran Bukit Raja',
                'postcode' => 41150,
                'city' => 'KLANG',
                'state' => 'SELANGOR',
                'status' => 'Created',
                'type' => 'Site',
                'link' => NULL,
                'creator_id' => 0,
                'updated_at' => '2024-11-20 19:01:22',
                'created_at' => '2024-11-20 19:01:18',
            ),
            2 =>
            array(
                'id' => 2,
                'address_id' => 2,
                'latitude' => '3.3144165',
                'longitude' => '101.4142867',
                'name' => NULL,
                'address_1' => 'Lot 769-1/2, Lot 770-1/2',
                'address_2' => 'Jalan Kuala SELANGOR',
                'postcode' => 45600,
                'city' => 'BESTARI JAYA',
                'state' => 'SELANGOR',
                'status' => 'Created',
                'type' => 'Office',
                'link' => NULL,
                'creator_id' => 0,
                'updated_at' => '2024-11-20 19:01:26',
                'created_at' => '2024-11-20 19:01:24',
            ),
            3 =>
            array(
                'id' => 3,
                'address_id' => 3,
                'latitude' => '3.3127083',
                'longitude' => '101.3955861',
                'name' => NULL,
                'address_1' => 'No. 242, Kampung Baru Ijok',
                'address_2' => 'Simpang Ijok',
                'postcode' => 41150,
                'city' => 'BESTARI JAYA',
                'state' => 'SELANGOR',
                'status' => 'Created',
                'type' => 'Office',
                'link' => NULL,
                'creator_id' => 0,
                'updated_at' => '2024-11-20 19:01:30',
                'created_at' => '2024-11-20 19:01:28',
            ),
            4 =>
            array(
                'id' => 4,
                'address_id' => 4,
                'latitude' => '3.0652032',
                'longitude' => '101.4614516',
                'name' => NULL,
                'address_1' => 'A-18-3A, Blok A, Pangsapuri Palm Garden',
                'address_2' => 'Persiaran Bukit Raja',
                'postcode' => 41150,
                'city' => 'KLANG',
                'state' => 'SELANGOR',
                'status' => 'Created',
                'type' => 'Site',
                'link' => NULL,
                'creator_id' => 0,
                'updated_at' => '2024-11-20 19:01:34',
                'created_at' => '2024-11-20 19:01:32',
            ),
            5 =>
            array(
                'id' => 5,
                'address_id' => 5,
                'latitude' => '3.0878739',
                'longitude' => '101.4492158',
                'name' => NULL,
                'address_1' => 'No. 7, Lrg Astana 1A/KU2',
                'address_2' => 'Bandar Bukit Raja',
                'postcode' => 41050,
                'city' => 'KLANG',
                'state' => 'SELANGOR',
                'status' => 'Created',
                'type' => 'Site',
                'link' => NULL,
                'creator_id' => 8,
                'updated_at' => '2024-11-20 19:01:39',
                'created_at' => '2024-11-20 19:01:36',
            ),
            6 =>
            array(
                'id' => 6,
                'address_id' => 6,
                'latitude' => '3.0559479',
                'longitude' => '101.4598543',
                'name' => NULL,
                'address_1' => '1, Jalan Lang',
                'address_2' => 'Taman Berkeley',
                'postcode' => 41150,
                'city' => 'KLANG',
                'state' => 'SELANGOR',
                'status' => 'Created',
                'type' => 'Site',
                'link' => NULL,
                'creator_id' => 8,
                'updated_at' => '2024-11-20 19:01:10',
                'created_at' => '2024-11-20 19:01:06',
            ),
            7 =>
            array(
                'id' => 7,
                'address_id' => 7,
                'latitude' => '3.0806646',
                'longitude' => '101.4510568',
                'name' => NULL,
                'address_1' => 'No 21, Persiaran Astana / KU 2',
                'address_2' => 'Bandar Bukit Raja',
                'postcode' => 41050,
                'city' => 'KLANG',
                'state' => 'SELANGOR',
                'status' => 'Created',
                'type' => 'Site',
                'link' => NULL,
                'creator_id' => 9,
                'updated_at' => '2024-11-20 19:01:44',
                'created_at' => '2024-11-20 19:01:41',
            ),
            8 =>
            array(
                'id' => 8,
                'address_id' => 8,
                'latitude' => '3.0554355',
                'longitude' => '101.4588752',
                'name' => NULL,
                'address_1' => '1, Jalan Angsa',
                'address_2' => 'Taman Berkeley',
                'postcode' => 41150,
                'city' => 'KLANG',
                'state' => 'SELANGOR',
                'status' => 'Created',
                'type' => 'Site',
                'link' => NULL,
                'creator_id' => 9,
                'updated_at' => '2024-11-20 19:01:04',
                'created_at' => '2024-11-20 19:01:00',
            ),
            9 =>
            array(
                'id' => 9,
                'address_id' => 9,
                'latitude' => '3.1748973',
                'longitude' => '101.5747634',
                'name' => NULL,
                'address_1' => 'NO.16&18, JLN PEKAKA 8/3,SEKSYEN 8, KOTA DAMANSARA,47810 PETALING JAYA,SELANGOR D.E.',
                'address_2' => 'SEKSYEN 8, KOTA DAMANSARA',
                'postcode' => 47810,
                'city' => 'PETALING JAYA',
                'state' => 'SELANGOR',
                'status' => 'Created',
                'type' => 'Office',
                'link' => NULL,
                'creator_id' => 0,
                'updated_at' => '2024-11-20 19:01:51',
                'created_at' => '2024-11-20 19:01:49',
            ),
            10 =>
            array(
                'id' => 10,
                'address_id' => 10,
                'latitude' => '3.1504559',
                'longitude' => '101.7486627',
                'name' => NULL,
                'address_1' => '57-2, JLN SULAIMAN 3,TAMAN PUTRA SULAIMAN,68000 AMPANG,SELANGOR D.E.',
                'address_2' => 'TAMAN PUTRA SULAIMAN',
                'postcode' => 68000,
                'city' => 'AMPANG',
                'state' => 'SELANGOR',
                'status' => 'Created',
                'type' => 'Office',
                'link' => NULL,
                'creator_id' => 0,
                'updated_at' => '2024-11-20 19:01:47',
                'created_at' => '2024-11-20 19:01:54',
            ),
            11 =>
            array(
                'id' => 11,
                'address_id' => 11,
                'latitude' => '2.9944035',
                'longitude' => '101.8069098',
                'name' => NULL,
                'address_1' => 'NO.9-1B,1ST FLR,BLK A,JLN SENTOSA 1,TAMAN SENTOSA,SUNGAI JELOK,43000 KAJANG,SEL D.E.',
                'address_2' => 'JLN SENTOSA 1,TAMAN SENTOSA',
                'postcode' => 43000,
                'city' => 'KAJANG',
                'state' => 'SELANGOR',
                'status' => 'Created',
                'type' => 'Office',
                'link' => NULL,
                'creator_id' => 0,
                'updated_at' => '2024-11-20 19:01:56',
                'created_at' => '2024-11-20 19:01:59',
            ),
            12 =>
            array(
                'id' => 12,
                'address_id' => 12,
                'latitude' => '3.0919468',
                'longitude' => '101.676651',
                'name' => NULL,
                'address_1' => 'NO.20-G, JALAN 3/114,KUCHAI BUSINESS CENTRE,OFF JALAN KUCHAI LAMA,58200 KUALA LUMPUR.',
                'address_2' => 'KUCHAI BUSINESS CENTRE',
                'postcode' => 58200,
                'city' => 'KUALA LUMPUR',
                'state' => 'WP KUALA LUMPUR',
                'status' => 'Created',
                'type' => 'Office',
                'link' => NULL,
                'creator_id' => 0,
                'updated_at' => '2024-11-20 19:02:06',
                'created_at' => '2024-11-20 19:02:09',
            ),
            13 =>
            array(
                'id' => 13,
                'address_id' => 13,
                'latitude' => '3.252634',
                'longitude' => '101.6502103',
                'name' => NULL,
                'address_1' => 'NO.12, JALAN 3/8,BANDAR BARU SELAYANG,66100 BATU CAVES,SELANGOR D.E.',
                'address_2' => 'BANDAR BARU SELAYANG',
                'postcode' => 68100,
                'city' => 'BATU CAVES',
                'state' => 'SELANGOR',
                'status' => 'Created',
                'type' => 'Office',
                'link' => NULL,
                'creator_id' => 0,
                'updated_at' => '2024-11-20 19:02:02',
                'created_at' => '2024-11-20 19:02:04',
            ),
            14 =>
            array(
                'id' => 14,
                'address_id' => 14,
                'latitude' => '3.0168527',
                'longitude' => '101.6161575',
                'name' => NULL,
                'address_1' => 'NO.69-2, JLN PUTERI 5/7,BANDAR PUTERI PUCHONG,47100 PUCHONG,SELANGOR.',
                'address_2' => 'BANDAR PUTERI PUCHONG',
                'postcode' => 47100,
                'city' => 'PUCHONG',
                'state' => 'SELANGOR',
                'status' => 'Created',
                'type' => 'Office',
                'link' => NULL,
                'creator_id' => 0,
                'updated_at' => '2024-11-20 19:02:12',
                'created_at' => '2024-11-20 19:02:15',
            ),
            15 =>
            array(
                'id' => 15,
                'address_id' => 15,
                'latitude' => '2.9897321',
                'longitude' => '101.6200691',
                'name' => NULL,
                'address_1' => 'NO.31-2ND FLR JLN BPU 8,BANDAR PUCHONG UTAMA,47100 PUCHONG,SELANGOR D.E.',
                'address_2' => 'BANDAR PUCHONG UTAMA',
                'postcode' => 47100,
                'city' => 'PUCHONG',
                'state' => 'SELANGOR',
                'status' => 'Created',
                'type' => 'Office',
                'link' => NULL,
                'creator_id' => 0,
                'updated_at' => '2024-11-20 19:02:26',
                'created_at' => '2024-11-20 19:02:22',
            ),
            16 =>
            array(
                'id' => 16,
                'address_id' => 16,
                'latitude' => '3.0375156',
                'longitude' => '101.5943372',
                'name' => NULL,
                'address_1' => 'SUB LOT 8,9,10,LOT 825,JLN SUBANG 6,TMN INDUSTRI SG,PENAGA,SUBANG INDUSTRIAL PARK,47510 SUBANG JAYA,SELANGOR.',
                'address_2' => 'JLN SUBANG 6,TMN INDUSTRI SG',
                'postcode' => 47620,
                'city' => 'SUBANG JAYA',
                'state' => 'SELANGOR',
                'status' => 'Created',
                'type' => 'Office',
                'link' => NULL,
                'creator_id' => 0,
                'updated_at' => '2024-11-20 19:02:17',
                'created_at' => '2024-11-20 19:02:20',
            ),
            17 =>
            array(
                'id' => 17,
                'address_id' => 17,
                'latitude' => '3.3213716',
                'longitude' => '101.5649426',
                'name' => NULL,
                'address_1' => 'NO 320/1458(LOT 6),JLN KUALA GARING UTAMA,TAMAN KUALA GARING,46000 RAWANG',
                'address_2' => 'JLN KUALA GARING UTAMA',
                'postcode' => 48000,
                'city' => 'RAWANG',
                'state' => 'SELANGOR',
                'status' => 'Created',
                'type' => 'Office',
                'link' => NULL,
                'creator_id' => 0,
                'updated_at' => '2024-11-20 19:01:02',
                'created_at' => '2024-11-20 19:00:54',
            ),
            18 =>
            array(
                'id' => 18,
                'address_id' => 18,
                'latitude' => '2.9940851',
                'longitude' => '101.4821904',
                'name' => NULL,
                'address_1' => 'NO:21B,LRG DATO SHAHBUDIN 20,TAMAN SENTOSA,41200 KLANG,SELANGOR.D.E,',
                'address_2' => 'TAMAN SENTOSA',
                'postcode' => 41200,
                'city' => 'KLANG',
                'state' => 'SELANGOR',
                'status' => 'Created',
                'type' => 'Office',
                'link' => NULL,
                'creator_id' => 0,
                'updated_at' => '2024-11-20 19:00:57',
                'created_at' => '2024-11-20 19:00:56',
            ),
            19 =>
            array(
                'id' => 19,
                'address_id' => 19,
                'latitude' => '3.1308304',
                'longitude' => '101.7546486',
                'name' => NULL,
                'address_1' => 'NO.12-B JLN PANDAN INDAH 4/6A,PANDAN INDAH,55100 KUALA LUMPUR,',
                'address_2' => 'PANDAN INDAH',
                'postcode' => 55100,
                'city' => 'KUALA LUMPUR',
                'state' => 'WP KUALA LUMPUR',
                'status' => 'Created',
                'type' => 'Office',
                'link' => NULL,
                'creator_id' => 0,
                'updated_at' => '2024-11-20 19:00:50',
                'created_at' => '2024-11-20 19:00:46',
            ),
            20 =>
            array(
                'id' => 20,
                'address_id' => 20,
                'latitude' => '5.3955381',
                'longitude' => '100.3992395',
                'name' => NULL,
                'address_1' => 'NO 18,TINGKAT 1,JALAN TODAK 4,PUSAT BANDAR SEBERANG JAYA,13700 PERAI,PENANG,',
                'address_2' => 'PUSAT BANDAR SEBERANG JAYA,',
                'postcode' => 13700,
                'city' => 'PERAI',
                'state' => 'PULAU PINANG',
                'status' => 'Created',
                'type' => 'Office',
                'link' => NULL,
                'creator_id' => 0,
                'updated_at' => '2024-11-20 19:00:44',
                'created_at' => '2024-11-20 19:00:41',
            ),
            21 =>
            array(
                'id' => 21,
                'address_id' => 21,
                'latitude' => '3.0136906',
                'longitude' => '101.6152551',
                'name' => NULL,
                'address_1' => 'NO 40-2, JLN PUTERI 5/1,BDR PUTERI PUCHONG,47100 PUCHONG,SELANGOR D.E.',
                'address_2' => 'BDR PUTERI PUCHONG',
                'postcode' => 47100,
                'city' => 'PUCHONG',
                'state' => 'SELANGOR',
                'status' => 'Created',
                'type' => 'Office',
                'link' => NULL,
                'creator_id' => 0,
                'updated_at' => '2024-11-20 19:00:39',
                'created_at' => '2024-11-20 19:00:37',
            ),
            22 =>
            array(
                'id' => 22,
                'address_id' => 22,
                'latitude' => '3.1199684',
                'longitude' => '101.6000811',
                'name' => NULL,
                'address_1' => 'NO.12-3A (FRONT UNIT), 2ND FLR,JLN PJU 1/3B, SUNWAY MAS,COMMERCIAL CENTRE 47301,PJ SEL. D.E.',
                'address_2' => 'JLN PJU 1/3B, SUNWAY MAS',
                'postcode' => 47301,
                'city' => 'PETALING JAYA',
                'state' => 'SELANGOR',
                'status' => 'Created',
                'type' => 'Office',
                'link' => NULL,
                'creator_id' => 0,
                'updated_at' => '2024-11-20 19:00:35',
                'created_at' => '2024-11-20 19:00:31',
            ),
            23 =>
            array(
                'id' => 23,
                'address_id' => 23,
                'latitude' => '3.1191446',
                'longitude' => '101.5982664',
                'name' => NULL,
                'address_1' => '110-2A& 110-2B (1ST FLOOR),JLN PJU 1/3B,SUNWAYMAS COMMERCIAL CENTRE,47301 PETALING JAYA, SEL D.E',
                'address_2' => 'JLN PJU 1/3B',
                'postcode' => 47301,
                'city' => 'PETALING JAYA',
                'state' => 'SELANGOR',
                'status' => 'Created',
                'type' => 'Office',
                'link' => NULL,
                'creator_id' => 0,
                'updated_at' => '2024-11-20 19:00:29',
                'created_at' => '2024-11-20 19:00:26',
            ),
            24 =>
            array(
                'id' => 24,
                'address_id' => 24,
                'latitude' => '3.1528574',
                'longitude' => '101.7072207',
                'name' => NULL,
                'address_1' => 'DEVELOPMENT CONST DIVISION,13TH FLR, MENARA HAP SENG,JLN P RAMLEE, 50250 KL,',
                'address_2' => '13TH FLR, MENARA HAP SENG',
                'postcode' => 50250,
                'city' => 'KUALA LUMPUR',
                'state' => 'WP KUALA LUMPUR',
                'status' => 'Created',
                'type' => 'Office',
                'link' => NULL,
                'creator_id' => 0,
                'updated_at' => '2024-11-20 19:00:24',
                'created_at' => '2024-11-20 19:00:20',
            ),
            25 =>
            array(
                'id' => 25,
                'address_id' => 25,
                'latitude' => '3.2161353',
                'longitude' => '101.6159606',
                'name' => NULL,
                'address_1' => '44-3-1, Jln 3/62D,Medan Putra Business Centre,Bandar Sri Manjalara,Off Jalan Sri Damansara, 52200',
                'address_2' => 'Medan Putra Business Centre,',
                'postcode' => 52100,
                'city' => 'KUALA LUMPUR',
                'state' => 'WP KUALA LUMPUR',
                'status' => 'Created',
                'type' => 'Office',
                'link' => NULL,
                'creator_id' => 0,
                'updated_at' => '2024-11-20 19:00:17',
                'created_at' => '2024-11-20 19:00:13',
            ),
            26 =>
            array(
                'id' => 26,
                'address_id' => 26,
                'latitude' => '3.0244856',
                'longitude' => '101.5812759',
                'name' => NULL,
                'address_1' => 'NO.12 USJ 21/7,',
                'address_2' => NULL,
                'postcode' => 47630,
                'city' => 'SUBANG JAYA',
                'state' => 'SELANGOR',
                'status' => 'Created',
                'type' => 'Office',
                'link' => NULL,
                'creator_id' => 0,
                'updated_at' => '2024-11-20 19:00:10',
                'created_at' => '2024-11-20 19:00:07',
            ),
            27 =>
            array(
                'id' => 27,
                'address_id' => 27,
                'latitude' => '6.1683547',
                'longitude' => '100.3692647',
                'name' => NULL,
                'address_1' => 'NO 44, TAMAN SERI PANTAI',
                'address_2' => 'PANTAI JOHOR',
                'postcode' => 5250,
                'city' => 'ALOR SETAR',
                'state' => 'KEDAH',
                'status' => 'Created',
                'type' => 'Billing',
                'link' => NULL,
                'creator_id' => 4,
                'updated_at' => '2024-12-17 09:36:01',
                'created_at' => '2024-12-17 09:36:01',
            ),
            28 =>
            array(
                'id' => 29,
                'address_id' => 29,
                'latitude' => '3.0622839',
                'longitude' => '101.4632881',
                'name' => NULL,
                'address_1' => '102, PERSIARAN RAJAWALI/KU 1',
                'address_2' => 'BANDAR BARU KLANG',
                'postcode' => 41150,
                'city' => 'KLANG',
                'state' => 'SELANGOR',
                'status' => 'Created',
                'type' => 'Site',
                'link' => NULL,
                'creator_id' => 4,
                'updated_at' => '2024-12-17 09:39:19',
                'created_at' => '2024-12-17 09:39:19',
            ),
            29 =>
            array(
                'id' => 30,
                'address_id' => 30,
                'latitude' => '3.2335777',
                'longitude' => '101.7025847',
                'name' => NULL,
                'address_1' => 'NO 15, JALAN 6',
                'address_2' => 'TAMAN BATU OFF GREENWOOD PARK',
                'postcode' => 68100,
                'city' => 'BATU CAVES',
                'state' => 'SELANGOR',
                'status' => 'Created',
                'type' => 'Site',
                'link' => NULL,
                'creator_id' => 4,
                'updated_at' => '2024-12-17 09:39:52',
                'created_at' => '2024-12-17 09:39:52',
            ),
            30 =>
            array(
                'id' => 31,
                'address_id' => 31,
                'latitude' => '3.218405',
                'longitude' => '101.5356345',
                'name' => NULL,
                'address_1' => 'NO 2, JALAN BL 1',
                'address_2' => 'TAMAN BAYU LAGENDA',
                'postcode' => 48000,
                'city' => 'RAWANG',
                'state' => 'SELANGOR',
                'status' => 'Created',
                'type' => 'Billing',
                'link' => NULL,
                'creator_id' => 4,
                'updated_at' => '2024-12-17 10:13:13',
                'created_at' => '2024-12-17 10:13:13',
            ),
            31 =>
            array(
                'id' => 28,
                'address_id' => 28,
                'latitude' => '3.065107',
                'longitude' => '101.4615299',
                'name' => NULL,
                'address_1' => 'A-18-3A, BLOK A, PANGSAPURI PALM GARDEN',
                'address_2' => 'PERSIARAN BUKIT RAJA',
                'postcode' => 41150,
                'city' => 'KLANG',
                'state' => 'SELANGOR',
                'status' => 'Created',
                'type' => 'Billing',
                'link' => NULL,
                'creator_id' => 4,
                'updated_at' => '2024-12-17 09:38:22',
                'created_at' => '2024-12-17 09:38:22',
            ),
            32 =>
            array(
                'id' => 32,
                'address_id' => 32,
                'latitude' => '3.116',
                'longitude' => '101.8136045',
                'name' => NULL,
                'address_1' => 'SEKOLAH KEBANGSAAN TUN ABDUL AZIZ MAJID (SKTAAM), JALAN HULU LANGAT, PEKAN BATU 14 HULU LANGAT, HULU LANGAT, SELANGOR, MALAYSIA',
                'address_2' => '',
                'postcode' => 43100,
                'city' => 'HULU LANGAT',
                'state' => 'SELANGOR',
                'status' => 'Created',
                'type' => 'Site',
                'link' => NULL,
                'creator_id' => 4,
                'updated_at' => '2025-01-07 11:15:45',
                'created_at' => '2025-01-07 11:15:45',
            ),
        ));
    }
}
