<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TruckDetailsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('truck_details')->insert(array(
            0 =>
            array(
                'id' => 1,
                'truck_id' => 1,
                'model' => 'HOHAN',
                'length' => '29',
                'width' => '1',
                'height' => '12',
                'wheel_id' => 10,
                'status' => 'Pending',
                'creator_id' => 0,
                'updated_at' => '2024-03-26 16:24:38+00',
                'created_at' => '2024-03-26 16:24:38+00',
            ),
            1 =>
            array(
                'id' => 2,
                'truck_id' => 1,
                'model' => 'HOHAN',
                'length' => '29',
                'width' => '1',
                'height' => '12',
                'wheel_id' => 10,
                'status' => 'Active',
                'creator_id' => 0,
                'updated_at' => '2024-08-26 16:17:35+00',
                'created_at' => '2024-08-26 16:17:35+00',
            ),
            2 =>
            array(
                'id' => 3,
                'truck_id' => 1,
                'model' => 'HOHAN',
                'length' => '29',
                'width' => '1',
                'height' => '12',
                'wheel_id' => 10,
                'status' => 'Active',
                'creator_id' => 0,
                'updated_at' => '2024-07-05 09:22:37+00',
                'created_at' => '2024-07-05 09:22:37+00',
            ),
            3 =>
            array(
                'id' => 4,
                'truck_id' => 1,
                'model' => 'HOHAN',
                'length' => '29',
                'width' => '1',
                'height' => '12',
                'wheel_id' => 10,
                'status' => 'Active',
                'creator_id' => 0,
                'updated_at' => '2024-08-07 21:37:13+00',
                'created_at' => '2024-08-07 21:37:13+00',
            ),
            4 =>
            array(
                'id' => 5,
                'truck_id' => 1,
                'model' => 'HOHAN',
                'length' => '29',
                'width' => '1',
                'height' => '12',
                'wheel_id' => 10,
                'status' => 'Active',
                'creator_id' => 0,
                'updated_at' => '2024-03-26 16:49:08+00',
                'created_at' => '2024-03-26 16:49:08+00',
            ),
            5 =>
            array(
                'id' => 6,
                'truck_id' => 2,
                'model' => 'HINO',
                'length' => '45',
                'width' => '1',
                'height' => '15',
                'wheel_id' => 10,
                'status' => 'Pending',
                'creator_id' => 0,
                'updated_at' => '2024-03-26 16:50:10+00',
                'created_at' => '2024-03-26 16:50:10+00',
            ),
            6 =>
            array(
                'id' => 7,
                'truck_id' => 2,
                'model' => 'HINO',
                'length' => '45',
                'width' => '1',
                'height' => '15',
                'wheel_id' => 10,
                'status' => 'Active',
                'creator_id' => 0,
                'updated_at' => '2024-03-26 16:55:47+00',
                'created_at' => '2024-03-26 16:55:47+00',
            ),
            7 =>
            array(
                'id' => 8,
                'truck_id' => 2,
                'model' => 'HINO',
                'length' => '45',
                'width' => '1',
                'height' => '15',
                'wheel_id' => 10,
                'status' => 'Active',
                'creator_id' => 0,
                'updated_at' => '2024-08-21 10:01:11+00',
                'created_at' => '2024-08-21 10:01:11+00',
            ),
            8 =>
            array(
                'id' => 9,
                'truck_id' => 3,
                'model' => 'HOHAN',
                'length' => '12',
                'width' => '4',
                'height' => '12',
                'wheel_id' => 10,
                'status' => 'Active',
                'creator_id' => 0,
                'updated_at' => '2024-09-21 14:29:30+00',
                'created_at' => '2024-09-21 14:29:30+00',
            ),
            9 =>
            array(
                'id' => 10,
                'truck_id' => 3,
                'model' => 'HOHAN',
                'length' => '12',
                'width' => '4',
                'height' => '12',
                'wheel_id' => 10,
                'status' => 'Pending',
                'creator_id' => 0,
                'updated_at' => '2024-03-26 16:58:30+00',
                'created_at' => '2024-03-26 16:58:30+00',
            ),
            10 =>
            array(
                'id' => 11,
                'truck_id' => 3,
                'model' => 'HOHAN',
                'length' => '12',
                'width' => '4',
                'height' => '12',
                'wheel_id' => 10,
                'status' => 'Active',
                'creator_id' => 0,
                'updated_at' => '2024-03-26 17:00:59+00',
                'created_at' => '2024-03-26 17:00:59+00',
            ),
            11 =>
            array(
                'id' => 12,
                'truck_id' => 3,
                'model' => 'HOHAN',
                'length' => '12',
                'width' => '4',
                'height' => '12',
                'wheel_id' => 10,
                'status' => 'Deleted',
                'creator_id' => 0,
                'updated_at' => '2024-06-11 14:51:13+00',
                'created_at' => '2024-06-11 14:51:13+00',
            ),
            12 =>
            array(
                'id' => 13,
                'truck_id' => 3,
                'model' => 'HOHAN',
                'length' => '12',
                'width' => '4',
                'height' => '12',
                'wheel_id' => 10,
                'status' => 'Active',
                'creator_id' => 0,
                'updated_at' => '2024-07-10 12:13:05+00',
                'created_at' => '2024-07-10 12:12:52+00',
            ),
            13 =>
            array(
                'id' => 14,
                'truck_id' => 3,
                'model' => 'HOHAN',
                'length' => '12',
                'width' => '4',
                'height' => '12',
                'wheel_id' => 10,
                'status' => 'Active',
                'creator_id' => 0,
                'updated_at' => '2024-07-10 12:14:06+00',
                'created_at' => '2024-07-10 12:14:06+00',
            ),
            14 =>
            array(
                'id' => 15,
                'truck_id' => 4,
                'model' => 'HOHAN',
                'length' => '12',
                'width' => '4',
                'height' => '12',
                'wheel_id' => 10,
                'status' => 'Pending',
                'creator_id' => 0,
                'updated_at' => '2024-03-26 16:59:19+00',
                'created_at' => '2024-03-26 16:59:19+00',
            ),
            15 =>
            array(
                'id' => 16,
                'truck_id' => 4,
                'model' => 'HOHAN',
                'length' => '12',
                'width' => '4',
                'height' => '12',
                'wheel_id' => 10,
                'status' => 'Active',
                'creator_id' => 0,
                'updated_at' => '2024-03-26 17:01:05+00',
                'created_at' => '2024-03-26 17:01:05+00',
            ),
            16 =>
            array(
                'id' => 17,
                'truck_id' => 4,
                'model' => 'HOHAN',
                'length' => '12',
                'width' => '4',
                'height' => '12',
                'wheel_id' => 10,
                'status' => 'Active',
                'creator_id' => 0,
                'updated_at' => '2024-06-19 11:56:59+00',
                'created_at' => '2024-06-19 11:56:59+00',
            ),
            17 =>
            array(
                'id' => 18,
                'truck_id' => 4,
                'model' => 'HOHAN',
                'length' => '12',
                'width' => '4',
                'height' => '12',
                'wheel_id' => 10,
                'status' => 'Active',
                'creator_id' => 0,
                'updated_at' => '2024-06-11 14:49:18+00',
                'created_at' => '2024-06-11 14:49:18+00',
            ),
            18 =>
            array(
                'id' => 19,
                'truck_id' => 4,
                'model' => 'HOHAN',
                'length' => '12',
                'width' => '4',
                'height' => '12',
                'wheel_id' => 10,
                'status' => 'Active',
                'creator_id' => 0,
                'updated_at' => '2024-08-05 10:56:57+00',
                'created_at' => '2024-08-05 10:56:57+00',
            ),
            19 =>
            array(
                'id' => 20,
                'truck_id' => 4,
                'model' => 'HOHAN',
                'length' => '12',
                'width' => '4',
                'height' => '12',
                'wheel_id' => 10,
                'status' => 'Active',
                'creator_id' => 0,
                'updated_at' => '2024-06-14 11:38:36+00',
                'created_at' => '2024-06-14 11:38:36+00',
            ),
            20 =>
            array(
                'id' => 21,
                'truck_id' => 4,
                'model' => 'HOHAN',
                'length' => '12',
                'width' => '4',
                'height' => '12',
                'wheel_id' => 10,
                'status' => 'Active',
                'creator_id' => 0,
                'updated_at' => '2024-06-17 12:14:18+00',
                'created_at' => '2024-06-17 12:14:18+00',
            ),
            21 =>
            array(
                'id' => 22,
                'truck_id' => 4,
                'model' => 'HOHAN',
                'length' => '12',
                'width' => '4',
                'height' => '12',
                'wheel_id' => 10,
                'status' => 'Deleted',
                'creator_id' => 0,
                'updated_at' => '2024-06-18 10:26:12+00',
                'created_at' => '2024-06-18 10:26:12+00',
            ),
            22 =>
            array(
                'id' => 23,
                'truck_id' => 4,
                'model' => 'HOHAN',
                'length' => '12',
                'width' => '4',
                'height' => '12',
                'wheel_id' => 10,
                'status' => 'Active',
                'creator_id' => 0,
                'updated_at' => '2024-06-19 11:48:56+00',
                'created_at' => '2024-06-19 11:48:44+00',
            ),
            23 =>
            array(
                'id' => 24,
                'truck_id' => 5,
                'model' => 'HOHAN',
                'length' => '12',
                'width' => '4',
                'height' => '12',
                'wheel_id' => 12,
                'status' => 'Active',
                'creator_id' => 0,
                'updated_at' => '2024-03-26 17:01:24+00',
                'created_at' => '2024-03-26 17:01:24+00',
            ),
            24 =>
            array(
                'id' => 25,
                'truck_id' => 5,
                'model' => 'HOHAN',
                'length' => '12',
                'width' => '4',
                'height' => '12',
                'wheel_id' => 12,
                'status' => 'Pending',
                'creator_id' => 0,
                'updated_at' => '2024-03-26 17:00:15+00',
                'created_at' => '2024-03-26 17:00:15+00',
            ),
            25 =>
            array(
                'id' => 26,
                'truck_id' => 6,
                'model' => 'HOHAN',
                'length' => '29',
                'width' => '1',
                'height' => '12',
                'wheel_id' => 6,
                'status' => 'Pending',
                'creator_id' => 0,
                'updated_at' => '2024-06-12 07:56:09+00',
                'created_at' => '2024-06-12 15:29:44+00',
            ),
            26 =>
            array(
                'id' => 27,
                'truck_id' => 6,
                'model' => 'HOHAN',
                'length' => '29',
                'width' => '1',
                'height' => '12',
                'wheel_id' => 6,
                'status' => 'Active',
                'creator_id' => 0,
                'updated_at' => '2024-06-12 15:27:51+00',
                'created_at' => '2024-06-12 15:27:47+00',
            ),
            27 =>
            array(
                'id' => 28,
                'truck_id' => 6,
                'model' => 'HOHAN',
                'length' => '29',
                'width' => '1',
                'height' => '12',
                'wheel_id' => 10,
                'status' => 'Active',
                'creator_id' => 0,
                'updated_at' => '2024-06-12 08:17:08+00',
                'created_at' => '2024-06-12 07:55:44+00',
            ),
            28 =>
            array(
                'id' => 29,
                'truck_id' => 7,
                'model' => 'HOHAN',
                'length' => '12',
                'width' => '12',
                'height' => '12',
                'wheel_id' => 10,
                'status' => 'Pending',
                'creator_id' => 0,
                'updated_at' => '2024-06-12 16:20:47+00',
                'created_at' => '2024-06-12 16:20:43+00',
            ),
            29 =>
            array(
                'id' => 30,
                'truck_id' => 7,
                'model' => 'HOHAN',
                'length' => '12',
                'width' => '12',
                'height' => '12',
                'wheel_id' => 10,
                'status' => 'Active',
                'creator_id' => 0,
                'updated_at' => '2024-06-12 16:22:02+00',
                'created_at' => '2024-06-12 16:22:02+00',
            ),
            30 =>
            array(
                'id' => 31,
                'truck_id' => 7,
                'model' => 'HOHAN',
                'length' => '12',
                'width' => '12',
                'height' => '12',
                'wheel_id' => 10,
                'status' => 'Active',
                'creator_id' => 0,
                'updated_at' => '2024-06-12 08:21:24+00',
                'created_at' => '2024-06-12 08:21:16+00',
            ),
            31 =>
            array(
                'id' => 32,
                'truck_id' => 8,
                'model' => 'HOHAN',
                'length' => '12',
                'width' => '4',
                'height' => '12',
                'wheel_id' => 10,
                'status' => 'Active',
                'creator_id' => 0,
                'updated_at' => '2024-03-26 17:00:59+00',
                'created_at' => '2024-03-26 17:00:59+00',
            ),
            32 =>
            array(
                'id' => 33,
                'truck_id' => 8,
                'model' => 'HOHAN',
                'length' => '12',
                'width' => '4',
                'height' => '12',
                'wheel_id' => 10,
                'status' => 'Deleted',
                'creator_id' => 0,
                'updated_at' => '2024-06-11 14:51:13+00',
                'created_at' => '2024-06-11 14:51:13+00',
            ),
            33 =>
            array(
                'id' => 34,
                'truck_id' => 8,
                'model' => 'HOHAN',
                'length' => '12',
                'width' => '4',
                'height' => '12',
                'wheel_id' => 10,
                'status' => 'Active',
                'creator_id' => 0,
                'updated_at' => '2024-07-10 12:13:05+00',
                'created_at' => '2024-07-10 12:12:52+00',
            ),
        ));
    }
}
