<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert(array(
            1 =>
            array(
                'id' => 1,
                'name' => 'Changshi Sdn. Bhd.',
                'email' => 'changahisdnbhd@ymail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$30BNthsmd4ObnHqk9AjSTu4OUhsDDp9cBY9DQC7MvK1fJ5b3orsSG',
                'remember_token' => 'OFpq6YLXod',
                'profile_photo_path' => NULL,
                'sound_notification' => true,
                'updated_at' => '2024-05-11 23:52:49+00',
                'created_at' => '2024-05-11 23:52:49+00',
                'demo' => false,
                'country_code' => 'Malaysia',
                'phone' => '60332792288',
                'phone_verified_at' => NULL,
                'address_id' => 0,
            ),
            2 =>
            array(
                'id' => 2,
                'name' => 'Popular Pillar Sdn. Bhd.',
                'email' => 'popularpillar@gmail.com',
                'email_verified_at' => '2023-12-13 11:49:45',
                'password' => '$2y$10$4LFuGXIs4M2AiBhZP4VzY..H3QUtkMHh3Z1Nc0OCbnksts2fchm2O',
                'remember_token' => 'tU8PoG55C6',
                'profile_photo_path' => NULL,
                'sound_notification' => true,
                'updated_at' => '2024-05-11 23:52:49+00',
                'created_at' => '2024-05-11 23:52:49+00',
                'demo' => false,
                'country_code' => 'Malaysia',
                'phone' => '60182059770',
                'phone_verified_at' => NULL,
                'address_id' => 0,
            ),
            3 =>
            array(
                'id' => 3,
                'name' => 'Oasis Polygon Sdn. Bhd.',
                'email' => 'oasispolygon@gmail.com',
                'email_verified_at' => '2023-12-13 11:49:45',
                'password' => '$2y$10$QbbFjt.ahI6rYr/ZYkekA.hRvviEZ7geLS/ZGdWGOCdA2LdwIEve.',
                'remember_token' => 'BNcTlTOKnz',
                'profile_photo_path' => NULL,
                'sound_notification' => true,
                'updated_at' => '2024-05-11 23:52:49+00',
                'created_at' => '2024-05-11 23:52:49+00',
                'demo' => false,
                'country_code' => 'Malaysia',
                'phone' => '6066188621',
                'phone_verified_at' => NULL,
                'address_id' => 0,
            ),
            4 =>
            array(
                'id' => 7,
                'name' => 'Ivy',
                'email' => 'ivy@sandpitnquarry.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$ENhCcZvTEKnKbdxMJ0OaWOgXYgRfqPATTy2Yn3HCw1BJqlIJNp93C',
                'remember_token' => 'LfStHnCRzj',
                'profile_photo_path' => NULL,
                'sound_notification' => true,
                'updated_at' => '2024-05-11 23:52:49+00',
                'created_at' => '2024-05-11 23:52:49+00',
                'demo' => false,
                'country_code' => 'Malaysia',
                'phone' => NULL,
                'phone_verified_at' => NULL,
                'address_id' => 0,
            ),
            5 =>
            array(
                'id' => 8,
                'name' => 'Irene',
                'email' => 'irene@sandpitnquarry.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Vpjrtzhg4IJbe4pR04c76usvhTVwZPGCS/c0kpycfHa3dv9ZramNy',
                'remember_token' => 'NTS1QsNgJh',
                'profile_photo_path' => NULL,
                'sound_notification' => true,
                'updated_at' => '2024-02-28 16:22:27+00',
                'created_at' => '2024-02-28 16:22:27+00',
                'demo' => false,
                'country_code' => 'Malaysia',
                'phone' => NULL,
                'phone_verified_at' => NULL,
                'address_id' => 0,
            ),
            6 =>
            array(
                'id' => 9,
                'name' => 'Hasrul Asapar',
                'email' => 'hasrul@sandpitnquarry.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$XeTHUFxm740Pgk1o4dBBbuAg.jqsIUOJnrc3/mDQlOTgjMd2sOw7O',
                'remember_token' => 'H2fXpiK5gC',
                'profile_photo_path' => NULL,
                'sound_notification' => true,
                'updated_at' => '2023-12-13 11:49:45+00',
                'created_at' => '2023-12-13 11:49:45+00',
                'demo' => false,
                'country_code' => 'Malaysia',
                'phone' => NULL,
                'phone_verified_at' => NULL,
                'address_id' => 0,
            ),
            7 =>
            array(
                'id' => 13,
                'name' => 'Conny',
                'email' => 'conny@sandpitnquarry.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$t2/CfNJzayqvjkAnyMhMreD5dQ6D1OJY56Ee6tTNxSUH3cZ0ZOGXO',
                'remember_token' => 'b6swpgDfzo',
                'profile_photo_path' => NULL,
                'sound_notification' => true,
                'updated_at' => '2024-05-11 23:52:50+00',
                'created_at' => '2024-05-11 23:52:50+00',
                'demo' => true,
                'country_code' => 'Malaysia',
                'phone' => NULL,
                'phone_verified_at' => NULL,
                'address_id' => 0,
            ),
            8 =>
            array(
                'id' => 14,
                'name' => 'BK',
                'email' => 'bk@sandpitnquarry.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$FbQYv.R9uttN4w63ddK.CedVSu9NZliAFOSMS.aptU4iyyQK6Hdqa',
                'remember_token' => 'sCwrgvv8MQ',
                'profile_photo_path' => NULL,
                'sound_notification' => true,
                'updated_at' => '2024-05-11 23:52:50+00',
                'created_at' => '2024-05-11 23:52:50+00',
                'demo' => false,
                'country_code' => 'Malaysia',
                'phone' => NULL,
                'phone_verified_at' => NULL,
                'address_id' => 0,
            ),
            9 =>
            array(
                'id' => 15,
                'name' => 'CSAR',
                'email' => 'csar@sandpitnquarry.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$rhO45wJVb6zClNkO1/.PKOJybNJ0HK18kB87MwYYasoEqtmLksGRS',
                'remember_token' => 'n5Oibb9Gax',
                'profile_photo_path' => NULL,
                'sound_notification' => true,
                'updated_at' => '2024-05-11 23:52:50+00',
                'created_at' => '2024-05-11 23:52:50+00',
                'demo' => false,
                'country_code' => 'Malaysia',
                'phone' => NULL,
                'phone_verified_at' => NULL,
                'address_id' => 0,
            ),
            10 =>
            array(
                'id' => 16,
                'name' => 'NTK',
                'email' => 'ntk@sandpitnquarry.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$a4jt1.p4CO2aSEh9JDroP.3aiZX1mn66y2Y1EGOgPG4APL1MgNGE6',
                'remember_token' => 'jpvp5sHkhJ',
                'profile_photo_path' => NULL,
                'sound_notification' => true,
                'updated_at' => '2024-04-18 15:12:17+00',
                'created_at' => '2024-04-18 15:12:17+00',
                'demo' => false,
                'country_code' => 'Malaysia',
                'phone' => NULL,
                'phone_verified_at' => NULL,
                'address_id' => 0,
            ),
            11 =>
            array(
                'id' => 10,
                'name' => 'Jess',
                'email' => 'jess@sandpitnquarry.com',
                'email_verified_at' => '2023-12-13 11:49:45',
                'password' => '$2y$10$Qj7W4QmlricRH3hjQgz6MO.6x51JNECSB0pXbtqAgKk.TuF/ToUzu',
                'remember_token' => 'Hl9ilvTDMY',
                'profile_photo_path' => NULL,
                'sound_notification' => true,
                'updated_at' => '2024-05-11 23:52:49+00',
                'created_at' => '2024-05-11 23:52:49+00',
                'demo' => false,
                'country_code' => 'Malaysia',
                'phone' => '60162051348',
                'phone_verified_at' => NULL,
                'address_id' => 0,
            ),
            12 =>
            array(
                'id' => 11,
                'name' => 'Ben',
                'email' => 'ben@sandpitnquarry.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$LcOB.b5bCDbHSYbaIWEaXu8aK2khEC4H1i/m1bZ.hoFNV1rYMEkZq',
                'remember_token' => 'BfAFwsd71z',
                'profile_photo_path' => NULL,
                'sound_notification' => true,
                'updated_at' => '2024-05-11 23:52:50+00',
                'created_at' => '2024-05-11 23:52:50+00',
                'demo' => false,
                'country_code' => 'Malaysia',
                'phone' => '60122052187',
                'phone_verified_at' => NULL,
                'address_id' => 0,
            ),
            13 =>
            array(
                'id' => 12,
                'name' => 'Jia Wen',
                'email' => 'jiawen@sandpitnquarry.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$I0OxuBAyIo2XKnffzWNoQO4vw5tGU5yJqFof2dLsmkKs2XILx4r/6',
                'remember_token' => 'P20vM7FB21',
                'profile_photo_path' => NULL,
                'sound_notification' => true,
                'updated_at' => '2024-05-11 23:52:50+00',
                'created_at' => '2024-05-11 23:52:50+00',
                'demo' => false,
                'country_code' => 'Malaysia',
                'phone' => '60166188624',
                'phone_verified_at' => NULL,
                'address_id' => 0,
            ),
            14 =>
            array(
                'id' => 17,
                'name' => 'LIM',
                'email' => 'lim@sandpitnquarry.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$MzsuS1YUBr4g4Gg74gpusu2jwifyPYKxRwiJ2C5ojwfuwngPlSkA2',
                'remember_token' => 'sOXe8JhJC2',
                'profile_photo_path' => NULL,
                'sound_notification' => true,
                'updated_at' => '2024-05-11 23:52:50+00',
                'created_at' => '2024-05-11 23:52:50+00',
                'demo' => false,
                'country_code' => 'Malaysia',
                'phone' => '',
                'phone_verified_at' => NULL,
                'address_id' => 0,
            ),
            15 =>
            array(
                'id' => 4,
                'name' => 'Ash',
                'email' => 'asyrani86@gmail.com',
                'email_verified_at' => '2024-05-11 23:52:49',
                'password' => '$2y$12$UPyc0n0hVs9Sk5HniPjUtebu9Db7CkYdZ3x40VxOgiNgmMJqyj6wO',
                'remember_token' => 'b1cdT7jHnzb6tzZBaZNRQRmpY7xgzlE26qV0gqCTzkNCAuieo3AyMdmzsy1x',
                'profile_photo_path' => NULL,
                'sound_notification' => true,
                'updated_at' => '2024-05-20 16:16:05+00',
                'created_at' => '2024-05-11 23:52:49+00',
                'demo' => true,
                'country_code' => 'Malaysia',
                'phone' => '60132465607',
                'phone_verified_at' => '2024-05-20 16:16:05',
                'address_id' => 0,
            ),
            16 =>
            array(
                'id' => 5,
                'name' => 'Nevin Raymon',
                'email' => 'nevin.raymonmd1190@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$e30/y59L4zVKegd0q678PeA.nCtrSvWg2ijTcOD/zW/.6qEKyDlFG',
                'remember_token' => '1hwFdaifcC',
                'profile_photo_path' => NULL,
                'sound_notification' => true,
                'updated_at' => '2024-06-10 19:50:33+00',
                'created_at' => '2024-05-11 23:52:49+00',
                'demo' => true,
                'country_code' => 'Malaysia',
                'phone' => '60143663466',
                'phone_verified_at' => '2024-06-10 19:50:33',
                'address_id' => 0,
            ),
            17 =>
            array(
                'id' => 22,
                'name' => 'Customer CS 2',
                'email' => 'customer.cs.2@sandpitnquarry.com',
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'profile_photo_path' => NULL,
                'sound_notification' => true,
                'updated_at' => '2024-11-20 10:24:10+00',
                'created_at' => '2024-11-20 10:24:12+00',
                'demo' => false,
                'country_code' => 'Malaysia',
                'phone' => NULL,
                'phone_verified_at' => NULL,
                'address_id' => 0,
            ),
            18 =>
            array(
                'id' => 6,
                'name' => 'Gugan',
                'email' => 'guganmanikam81@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$HcWZAKxGE.mxYTNr5hPXbOL/8XwhF65vFqqCMAGR3Ae5R5n/vUKtu',
                'remember_token' => 'iP5KM0vgXH',
                'profile_photo_path' => NULL,
                'sound_notification' => true,
                'updated_at' => '2023-12-13 11:49:45+00',
                'created_at' => '2023-12-13 11:49:45+00',
                'demo' => true,
                'country_code' => 'Malaysia',
                'phone' => '60164686783',
                'phone_verified_at' => NULL,
                'address_id' => 0,
            ),
            19 =>
            array(
                'id' => 19,
                'name' => 'Customer SNQ 1',
                'email' => 'customer.snq.1@sandpitnquarry.com',
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'profile_photo_path' => NULL,
                'sound_notification' => true,
                'updated_at' => '2024-11-20 10:21:22+00',
                'created_at' => '2024-11-20 10:21:24+00',
                'demo' => false,
                'country_code' => 'Malaysia',
                'phone' => NULL,
                'phone_verified_at' => NULL,
                'address_id' => 0,
            ),
            20 =>
            array(
                'id' => 20,
                'name' => 'Customer SNQ 2',
                'email' => 'customer.snq.2@sandpitnquarry.com',
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'profile_photo_path' => NULL,
                'sound_notification' => true,
                'updated_at' => '2024-11-20 10:22:45+00',
                'created_at' => '2024-11-20 10:22:47+00',
                'demo' => false,
                'country_code' => 'Malaysia',
                'phone' => NULL,
                'phone_verified_at' => NULL,
                'address_id' => 0,
            ),
            21 =>
            array(
                'id' => 21,
                'name' => 'Customer CS 1',
                'email' => 'customer.cs.1@sandpitnquarry.com',
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'profile_photo_path' => NULL,
                'sound_notification' => true,
                'updated_at' => '2024-11-20 10:23:38+00',
                'created_at' => '2024-11-20 10:23:41+00',
                'demo' => false,
                'country_code' => 'Malaysia',
                'phone' => NULL,
                'phone_verified_at' => NULL,
                'address_id' => 0,
            ),
            22 =>
            array(
                'id' => 23,
                'name' => 'Customer OP 1',
                'email' => 'customer.op.1@sandpitnquarry.com',
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'profile_photo_path' => NULL,
                'sound_notification' => true,
                'updated_at' => '2024-11-20 10:25:39+00',
                'created_at' => '2024-11-20 10:25:42+00',
                'demo' => false,
                'country_code' => 'Malaysia',
                'phone' => NULL,
                'phone_verified_at' => NULL,
                'address_id' => 0,
            ),
            23 =>
            array(
                'id' => 24,
                'name' => 'Customer OP 2',
                'email' => 'customer.op.2@sandpitnquarry.com',
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'profile_photo_path' => NULL,
                'sound_notification' => true,
                'updated_at' => '2024-11-20 10:26:10+00',
                'created_at' => '2024-11-20 10:26:13+00',
                'demo' => false,
                'country_code' => 'Malaysia',
                'phone' => NULL,
                'phone_verified_at' => NULL,
                'address_id' => 0,
            ),
            24 =>
            array(
                'id' => 25,
                'name' => 'Customer PP 1',
                'email' => 'customer.pp.1@sandpitnquarry.com',
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'profile_photo_path' => NULL,
                'sound_notification' => true,
                'updated_at' => '2024-11-20 10:26:39+00',
                'created_at' => '2024-11-20 10:26:42+00',
                'demo' => false,
                'country_code' => 'Malaysia',
                'phone' => NULL,
                'phone_verified_at' => NULL,
                'address_id' => 0,
            ),
            25 =>
            array(
                'id' => 26,
                'name' => 'Customer PP 2',
                'email' => 'customer.pp.2@sandpitnquarry.com',
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'profile_photo_path' => NULL,
                'sound_notification' => true,
                'updated_at' => '2024-11-20 10:27:24+00',
                'created_at' => '2024-11-20 10:27:28+00',
                'demo' => false,
                'country_code' => 'Malaysia',
                'phone' => NULL,
                'phone_verified_at' => NULL,
                'address_id' => 0,
            ),
            26 =>
            array(
                'id' => 27,
                'name' => 'Transporter 1',
                'email' => 'transporter.1@sandpitnquarry.com',
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'profile_photo_path' => NULL,
                'sound_notification' => true,
                'updated_at' => '2024-11-20 10:28:07+00',
                'created_at' => '2024-11-20 10:28:10+00',
                'demo' => false,
                'country_code' => 'Malaysia',
                'phone' => '601011112222',
                'phone_verified_at' => NULL,
                'address_id' => 0,
            ),
            27 =>
            array(
                'id' => 28,
                'name' => 'Driver 1 Transporter 1',
                'email' => 'driver.1.transporter.1@sandpitnquarry.com',
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'profile_photo_path' => NULL,
                'sound_notification' => true,
                'updated_at' => '2024-11-20 10:28:47+00',
                'created_at' => '2024-11-20 10:28:50+00',
                'demo' => false,
                'country_code' => 'Malaysia',
                'phone' => '601011113333',
                'phone_verified_at' => NULL,
                'address_id' => 0,
            ),
            28 =>
            array(
                'id' => 29,
                'name' => 'Driver 2 Transporter 1',
                'email' => 'driver.2.transporter.1@sandpitnquarry.com',
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'profile_photo_path' => NULL,
                'sound_notification' => true,
                'updated_at' => '2024-11-20 10:29:13+00',
                'created_at' => '2024-11-20 10:29:16+00',
                'demo' => false,
                'country_code' => 'Malaysia',
                'phone' => '601011114444',
                'phone_verified_at' => NULL,
                'address_id' => 0,
            ),
            29 =>
            array(
                'id' => 30,
                'name' => 'Transporter 2',
                'email' => 'transporter.2@sandpitnquarry.com',
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'profile_photo_path' => NULL,
                'sound_notification' => true,
                'updated_at' => '2024-11-20 10:29:47+00',
                'created_at' => '2024-11-20 10:29:50+00',
                'demo' => false,
                'country_code' => 'Malaysia',
                'phone' => '601022221111',
                'phone_verified_at' => NULL,
                'address_id' => 0,
            ),
            30 =>
            array(
                'id' => 31,
                'name' => 'Driver 1 Transporter 2',
                'email' => 'driver.1.transporter.2@sandpitnquarry.com',
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'profile_photo_path' => NULL,
                'sound_notification' => true,
                'updated_at' => '2024-11-20 10:30:19+00',
                'created_at' => '2024-11-20 10:30:22+00',
                'demo' => false,
                'country_code' => 'Malaysia',
                'phone' => '601022223333',
                'phone_verified_at' => NULL,
                'address_id' => 0,
            ),
            31 =>
            array(
                'id' => 32,
                'name' => 'Driver 2 Transporter 2',
                'email' => 'driver.2.transporter.2@sandpitnquarry.com',
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'profile_photo_path' => NULL,
                'sound_notification' => true,
                'updated_at' => '2024-11-20 10:30:56+00',
                'created_at' => '2024-11-20 10:30:58+00',
                'demo' => false,
                'country_code' => 'Malaysia',
                'phone' => '601022224444',
                'phone_verified_at' => NULL,
                'address_id' => 0,
            ),
            32 =>
            array(
                'id' => 3479,
                'name' => 'gugan',
                'email' => 'm.gugan2a.ictsmksm@gmail.com',
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'profile_photo_path' => NULL,
                'sound_notification' => true,
                'updated_at' => '2024-11-20 10:30:56+00',
                'created_at' => '2024-11-20 10:30:58+00',
                'demo' => false,
                'country_code' => 'Malaysia',
                'phone' => '601022224444',
                'phone_verified_at' => NULL,
                'address_id' => 0,
            ),
            33 =>
            array(
                'id' => 3480,
                'name' => 'Arif',
                'email' => 'farhanarif172@gmail.com',
                'email_verified_at' => NULL,
                'password' => NULL,
                'remember_token' => NULL,
                'profile_photo_path' => NULL,
                'sound_notification' => true,
                'updated_at' => '2024-11-20 10:30:56+00',
                'created_at' => '2024-11-20 10:30:58+00',
                'demo' => false,
                'country_code' => 'Malaysia',
                'phone' => '601022224444',
                'phone_verified_at' => NULL,
                'address_id' => 0,
            ),
        ));
    }
}
